spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:mysql://localhost:3306/restaurant
    username: smallboy
    password: abcd1234


oss:
  bucket-name: "yaojia-restaurant-dev"

jwt:
  expiration: 900000 # 15 minutes
  refresh-expiration: 86400000 # 1 day