spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:mysql://localhost:3306/restaurant
    username: smallboy
    password: abcd1234


oss:
  bucket-name: "yaojia-restaurant-dev"

jwt:
  expiration: 60000 # 1 minute
  refresh-expiration: 180000 # 3 minutes