spring:
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOSTNAME}:3306/restaurant
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


oss:
  bucket-name: "yaojia-restaurant-prod"

jwt:
  expiration: 1800000 # 30 minutes
  refresh-expiration: 2592000000 # 30 days
